version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
    BeforeInstall:
        - location: deploy_scripts/install.sh
          timeout: 300
          runas: ec2-user
    ApplicationStop:
        - location: deploy_scripts/stop.sh
          timeout: 300
          runas: ec2-user
    ApplicationStart:
        - location: deploy_scripts/start.sh
          timeout: 300
          runas: ec2-user
    ValidateService:
        - location: deploy_scripts/validate.sh
          timeout: 300
          runas: ec2-user
