version: 0.2

phases:
    install:
        commands:
          - npm install
          - npm install express --save
    build:
        commands:
          - npm test
cache:
    paths:
        - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
